<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
<?php
    echo $this->headTitle('Apigility');
    echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');
    echo $this->headLink(array('rel' => 'icon', 'type' => 'image/png', 'href' => $this->basePath('/img/favicon.png')))
        ->prependStylesheet($this->basePath('/zf-apigility/css/main.min.css'))
        ->prependStylesheet($this->basePath('/zf-apigility/css/bootstrap.min.css'));
    echo $this->headScript()
        ->prependFile($this->basePath('/zf-apigility/js/bootstrap.min.js'))
        ->prependFile($this->basePath('/zf-apigility/js/jquery.min.js'));
?>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Chair Roulette</title>

        <!-- Bootstrap -->

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        <script src="/js/jquery-2.1.3.min.js"></script>
        <script src="/js/bootstrap.min.js"></script>
    </head>
    <body>

    <nav class="navbar navbar-default navbar-fixed-top">
		  <div class="container-fluid">
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		      <a class="navbar-brand" href="/index.php">Chair Roulette</a>
		    </div>
		
		    <!-- Collect the nav links, forms, and other content for toggling -->
		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		      <ul class="nav navbar-nav">
		      <ul class="nav navbar-nav navbar-right">
		        <li class="dropdown">
		          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Links <span class="caret"></span></a>
		          <ul class="dropdown-menu" role="menu">
		            <li><a target="_blank" href="http://www.switchsystems.co.uk">Switch Systems Ltd</a></li>
		            <li><a target="_blank" href="http://www.twitter.com/switchsystems">Check us out on Twitter!</a></li>
		          </ul>
		        </li>
		      </ul>
		    </div><!-- /.navbar-collapse -->
		  </div><!-- /.container-fluid -->
		</nav>
    
        <?php echo $this->content; ?>

        <?php echo $this->inlineScript() ?>
    </body>
</html>
