<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
<?php
    echo $this->headTitle('Apigility');
    echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');
    echo $this->headLink(array('rel' => 'icon', 'type' => 'image/png', 'href' => $this->basePath('/img/favicon.png')))
        ->prependStylesheet($this->basePath('/zf-apigility/css/main.min.css'))
        ->prependStylesheet($this->basePath('/zf-apigility/css/bootstrap.min.css'));
    echo $this->headScript()
        ->prependFile($this->basePath('/zf-apigility/js/bootstrap.min.js'))
        ->prependFile($this->basePath('/zf-apigility/js/jquery.min.js'));
?>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Chair Roulette</title>

        <!-- Bootstrap -->

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        <script src="/js/jquery-2.1.3.min.js"></script>
        <script src="/js/app/game.js"></script>

    </head>
    <body>

            <?php echo $this->content; ?>


        <?php echo $this->inlineScript() ?>
    </body>
</html>
