<script src="/js/app/index.js"></script>
<div class="container">
	<div class="row">

		<div class="col-sm-6">
			Choose a game room from the right hand side, or create a new game for
			your friends

			<form id="newGame">
				<div class="form-group">
					<label for="name">Your Name</label> <input id="name" type="text"
						name="name" placeholder="Your name" required="required">
				</div>
				<button type="submit" class="btn btn-primary">Start New Game</button>
			</form>
		</div>
		<div class="col-sm-6">
			<div id="roomsList"></div>
		</div>
	</div>

</div>
