<script src="/js/app/index.js"></script>
<div class="container">
	<div class="row">

		<div class="col-sm-6">
		
			<img class="logo" src="/images/chair-roulette.png" width="640" height="280"/>
		
			Choose a game room from the right hand side, or create a new game for
			your friends. <em>You need to find at least 3 friends, so go ask people!</em> 

			<div class="well">
			<form id="newGame" method="post">
				<div class="form-group">
					<label for="name">Your Name</label> 
					<input id="name" type="text" name="name" placeholder="Your name" required="required">
				</div>
				<button type="submit" class="btn btn-primary">Start a New Game</button>
			</form>
			</div>
		</div>
		<div class="col-sm-6">
			<div id="roomsList"></div>
		</div>
	</div>
	
</div>

<script type="text/javascript">
<?php if (isset($this->roomName)) : ?>
	var createRoomName = "<?php echo $this->roomName;?>";
<?php else : ?>
	var createRoomName;
<?php endif;?>
</script>